### ISSUE TITLE
第一页有问题

### ISSUE THREAD

**Issue by gaocegege** [at15/SJTUThesis#4]
第一页都有很大的logo的
http://sjcg.jwc.sjtu.edu.cn/192/2015/2015/Dissertation.html

**Comment by at15** [comment]
交大logo下载 http://vi.sjtu.edu.cn/index.php/articles/bulletin/13

**Comment by at15** [comment]
好像新版的设计是统一用红色? 拉姆还是雷姆 /w\

**Comment by at15** [comment]
@gaocegege https://github.com/at15/SJTUThesis/tree/feature/title-page-logo https://github.com/at15/SJTUThesis/commit/fc19c5bc09c25865e8d78f3fee2b421d7ec66648 你测试一下，没问题了我再去开pr。

另外好像现在页面左上角的banner消失了。

**Comment by gaocegege** [comment]
Latexmk: 'pdflatex' needed too many passes
    ==> You will need to change a source file before I do another run <==

**Comment by at15** [comment]
@gaocegege 我猜是 dev 分支的问题, 我本本的linux硬盘装不下texlive了.... win下是正常的, 你试试直接根据diff改你现在的论文。

**Comment by gaocegege** [comment]
好，试试

**Comment by at15** [comment]
@gaocegege 所以策策你的结果是?

**Comment by at15** [comment]
@gaocegege 你最后是怎么处理的? 那次看你好像改成跟模板一样的了?

最简单的方法是word存成pdf然后include......

**Comment by gaocegege** [comment]
手写的，参考了@utf8please 的实现

**Comment by at15** [comment]
wow 这个么? https://github.com/gaocegege/SJTUThesis/commit/a6d37fc7dbf3c3865762721a59c24c38f6f52fc8

btw: 为什么不尝试开个pr呢

**Comment by at15** [comment]
... 你不 close 我都忘了...
